# site settings
title: Rami Awar
subtitle: 
email: rami.awar.research@gmail.com
description: A personal portfolio
baseurl: ""
url: "https://ramiawar.github.io"
author: Rami Awar
street_address: Walter-Sedlmayr Platz 6
city: Munich
zip_code: 80995
country: Germany
phone: (49) 1512 4454954

# homepage tiles
tiles-source: projects # accepts "posts" or "pages"
tiles-count: 12

collections:
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"

# social settings
500px_url:
facebook_url:
github_url: https://github.com/RamiAwar
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/ramiawar
linkedin_url: https://www.linkedin.com/in/ramiawarco
pinterest_url:
slack_url:
twitter_url: https://twitter.com/iamramiawar

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap
